---
functional:
  - Пользователь должен иметь возможность искать с помощью фильтра товары по ключевому слову или категории
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Сайту необходимо иметь порядковые страницы для просмотра товара
  
