---
functional:
  - Пользователь должен иметь возможность искать с помощью фильтра товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге должны быть сведения о товаре: название, рейтинг, цена со скидкой и без нее.
  - Пользователь может добавлять товар в корзину и продолжать выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины.
  - На странице корзины пользователь может оформить заказ с переходом на страницу оплаты.
  - На странице корзины пользователь может вернутся на главную страницу и продолжить выбирать товары в каталоге.
  - Корзина хранится в сессии браузера.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
implicit:
  - Сайту необходимо иметь порядковые страницы для просмотра товаров

 
